
siteName: Universal Health Coverage Data
analytics:
    legacy: false # true will implement the legacy analytics code instead of the latest
    basePath: /universal-health-coverage/coronavirus # prefix for analytics page identifiers
    channel: DEC Universal Health Coverage EXT
    environ: prod # (qa | prod)
exclude:
  - python
  - data
  - raw_material.md
  - README.md
  - jhu-map.html

dataViz: false   # true includes javascript for tableau
assetDir: "assets"  # path to img and css directory, relative to the page
documentRoot: /universal-health-coverage

# Note that defaults aren't recognized for github pages so you'll have to defined them all as front matter
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
      pageCategory: content page

      # optional page banner

      banner:
        pretitle: Sovereign
        title: Environmental, Social, and Governance Data
        subtitle: Data, Tools, and Stuff
        image:
          filename: banner2.jpg
          caption:  Banner image of a mountain and placid lake
